### ISSUE TITLE
User Story: Answer running poll anonymously

### ISSUE THREAD

**Issue by rhysshufflebotham** [rhysshufflebotham/love-running#1]
As a **user** I can **hide my identity** so that **I remain anonymous when answering the poll**.

# Acceptance criteria:

Acceptance criteria 1: User able to leave "Name" field blank.
Acceptance criteria 2: Placeholder text suggests to leave blank to remain anonymous.

# Tasks:

- [ ] Task 1: Remove "required" HTML from code.
- [ ]  Task 2: Add placeholder text "Leave blank if you wish to remain anonymous.
- [ ]  Task 3: Test that both blank and name input work correctly.
