### ISSUE TITLE
User Story: Add custom comments to poll.

### ISSUE THREAD

**Issue by rhysshufflebotham** [rhysshufflebotham/love-running#2]
As a **user** I can **add extra comments to the poll** so that **my feedback can be articulated effectively**.

# Acceptance criteria:
* Acceptance criteria 1: Additional comments box.
* Acceptance criteria 2: Enough space for user to express themselves fully.

# Tasks:

- [ ] Task 1: Write HTML for comments box.
- [ ]  Task 2: Write CSS styling for comments box.
- [ ]  Task 3: Test that comments of sufficient length are accepted,
